#اسم ملف المشروع 
name: thirdapp  
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  #لزم تكون المسافة بين جدار النافذ وكلمة assets 3
  assets:
    - images/image2.png

  